name: onegoal
description: OneGoal, is a reminder. Every day, this will remindes you, your main lifes goal.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar_carousel: ^1.4.12

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/

  fonts:
  - family: AmaticSC
    fonts:
    - asset: fonts/AmaticSC-Regular.ttf
